# Generated by Django 3.1.6 on 2021-02-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=15)),
                ('classification', models.CharField(max_length=100)),
                ('totalsites', models.CharField(max_length=10)),
                ('cost', models.CharField(max_length=10)),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(default='', max_length=200)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=15)),
                ('classification', models.CharField(max_length=100)),
                ('totalsites', models.CharField(max_length=10)),
                ('cost', models.CharField(max_length=10)),
                ('Image', models.ImageField(upload_to='')),
                ('directions', models.URLField()),
            ],
        ),
    ]
