# Generated by Django 3.1.6 on 2021-02-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campground',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='campground',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='campground',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='campground',
            name='totalsites',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='address',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='city',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='name',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='state',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='totalsites',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='zipcode',
        ),
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateField(verbose_name='Trip Date'),
        ),
    ]
