# Generated by Django 3.1.6 on 2021-02-04 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210204_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='campground',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='campground',
            name='directions',
            field=models.CharField(default='', max_length=200),
        ),
    ]
