# Generated by Django 3.1.6 on 2021-02-07 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_campground_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='reservation',
            new_name='reservation_link',
        ),
    ]
