# Generated by Django 3.1.6 on 2021-02-04 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='reservation',
            field=models.CharField(default='', max_length=500),
        ),
    ]
