# Generated by Django 3.1.6 on 2021-02-08 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_photo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='user',
        ),
        migrations.AddField(
            model_name='photo',
            name='campground',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.campground'),
            preserve_default=False,
        ),
    ]
