# Generated by Django 3.1.6 on 2021-02-09 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_campground_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='campground',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
